=== PolanieOnLine/PolanieOnLine/data/conf/producers.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
	xmlns:tns="http://www.example.org/productions" elementFormDefault="qualified"
	xmlns:Q2="stendhal">

	<element name="producers" type="Q2:Producer"/>
	<complexType name="Producer">
		<sequence>
			<element name="producer" type="Q2:Product" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>

	<complexType name="Product">
		<sequence>
			<element name="welcome" type="Q2:Text"/>
			<element name="item" type="Q2:ProductItem" minOccurs="1" maxOccurs="unbounded"/>
			<element name="activity" type="Q2:Activity"/>
			<element name="time" type="Q2:Time"/>
		</sequence>
		<attribute name="npc" type="string" use="required"/>
		<attribute name="slot" type="string" use="required"/>
		<attribute name="type" type="Q2:ProductType" use="required"/>
		<attribute name="condition" type="string" use="optional"/>
	</complexType>

	<complexType name="ProductItem">
		<sequence>
			<element name="resource" type="Q2:RequiredResources" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="name" type="string" use="required"/>
		<attribute name="quantity" type="positiveInteger" use="optional"/>
	</complexType>

	<simpleType name="ProductType">
		<restriction base="string">
			<enumeration value="food"/>
			<enumeration value="drink"/>
			<enumeration value="item"/>
		</restriction>
	</simpleType>

	<complexType name="RequiredResources">
		<attribute name="name" type="string" use="required"/>
		<attribute name="amount" type="positiveInteger" use="required"/>
	</complexType>

	<complexType name="Text">
		<attribute name="text" type="string"/>
	</complexType>

	<complexType name="Activity">
		<attribute name="type" type="string"/>
	</complexType>

	<complexType name="Time">
		<attribute name="value" type="positiveInteger"/>
	</complexType>

</schema>

=== PolanieOnLine/PolanieOnLine/data/conf/producers/foods.xml
<?xml version="1.0" encoding="UTF-8"?>

<producers xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../producers.xsd">

	<!-- Arlindo (Ados) -->
	<producer npc="Arlindo" slot="arlindo_make_pie" type="food">
		<welcome text="Witam! Założę się, że słyszałeś o moim słynnym placku. Mówiąc #upiecz zrobię go dla ciebie."/>
		<item name="tarta" minutes="7">
			<resource name="mąka" amount="2"/>
			<resource name="mięso" amount="2"/>
			<resource name="marchew"/>
			<resource name="pieczarka" amount="2"/>

			<activity type="make,zrób,upiecz"/>
		</item>
	</producer>

	<!-- Blacksheep Bob (Ados) -->
	<producer npc="Blacksheep Bob" slot="blacksheepbob_make_sausage" type="food">
		<welcome text="Hej! Witamy na naszym mięsnym targu Blacksheep. Czy mogę zrobić dla Ciebie paróweczki?"/>
		<item name="paróweczka" minutes="2">
			<resource name="truchło wampira"/>
			<resource name="truchło nietoperza"/>
			<resource name="mięso"/>
			<resource name="napój z winogron" amount="2"/>

			<activity type="make,zrób"/>
		</item>
	</producer>

	<!-- Blacksheep Harry (Ados) -->
	<producer npc="Blacksheep Harry" slot="blacksheepharry_make_tuna" type="food">
		<welcome text="Witamy na mięsnym targu Blacksheep. Czy mogę zrobić dla Ciebie prasowanego tuńczyka?"/>
		<item name="prasowany tuńczyk" minutes="2">
			<resource name="makrela"/>
			<resource name="okoń"/>
			<resource name="kolorowe kulki" amount="2"/>

			<activity type="make,zrób"/>
		</item>
	</producer>

	<!-- Blacksheep Joe (Ados) -->
	<producer npc="Blacksheep Joe" slot="blacksheepjoe_make_cheese_sausage" type="food">
		<welcome text="Witamy na mięsnym targu Blacksheep. Czy mogę zrobić dla Ciebie kiełbasę z serem?"/>
		<item name="kiełbasa serowa" minutes="2">
			<resource name="truchło wampira"/>
			<resource name="truchło nietoperza"/>
			<resource name="udko"/>
			<resource name="czarna perła"/>
			<resource name="ser"/>

			<activity type="make,zrób"/>
		</item>
	</producer>

	<!-- Linzo (Fado) -->
	<producer npc="Linzo" slot="linzo_make_fish_pie" type="food">
		<welcome text="Cześć, przyszedłeś spróbować moich rybnych placków? Mogę #upiec jeden dla Ciebie."/>
		<item name="tarta z rybnym nadzieniem" minutes="5">
			<resource name="mąka"/>
			<resource name="dorsz" amount="2"/>
			<resource name="makrela"/>
			<resource name="por"/>

			<activity type="make,zrób,upiecz"/>
		</item>
	</producer>

	<!-- Martha (Kalavan) -->
	<producer npc="Martha" slot="martha_bake_applepie" type="food">
		<welcome text="Cześć! Czy przyszedłeś, aby skosztować mojego pysznego jabłecznika? Mogę #upiec go dla Ciebie!"/>
		<item name="jabłecznik" minutes="15">
			<resource name="mąka" amount="2"/>
			<resource name="miód"/>
			<resource name="mleko"/>
			<resource name="jajo"/>
			<resource name="jabłko"/>

			<activity type="bake,zrób,upiecz"/>
		</item>
	</producer>

	<!-- Gertha (Kalavan) -->
	<producer npc="Gertha" slot="gertha_bake_cherrypie" type="food">
		<welcome text="Cześć! Czy przyszedłeś, aby skosztować mojego wspaniałego ciasta z wiśniami? Mogę z przyjemnością je dla Ciebie #upiec!"/>
		<item name="ciasto z wiśniami" minutes="15">
			<resource name="mąka" amount="2"/>
			<resource name="miód"/>
			<resource name="mleko"/>
			<resource name="jajo"/>
			<resource name="wisienka" amount="2"/>

			<activity type="bake,zrób,upiecz"/>
		</item>
	</producer>

	<!-- Gaston (Rat City) -->
	<producer npc="Gaston" slot="gaston_bake_crepesuzette" type="food">
		<welcome text="Witaj. Założe się, że przyszedłeś spróbować mojch pysznych #naleśników z polewą czekoladową! Mogę #upiec je dla Ciebie o ile chcesz."/>
		<item name="naleśniki z polewą czekoladową" minutes="5">
			<resource name="mąka"/>
			<resource name="mleko"/>
			<resource name="jajo"/>
			<resource name="osełka masła"/>
			<resource name="cukier"/>
			<resource name="tabliczka czekolady"/>
			<resource name="ekstrakt litworowy"/>

			<activity type="bake,zrób,upiecz"/>
		</item>
	</producer>

	<!-- Leander (Semos) -->
	<producer npc="Leander" slot="leander_make_sandwiches" type="food">
		<welcome text="Witaj w mojej piekarni, gdzie robię ciasto o zamorskiej nazwie #pizza oraz #kanapki!"/>
		<item name="kanapka" minutes="3">
			<resource name="chleb"/>
			<resource name="szynka"/>
			<resource name="ser" amount="2"/>

			<activity type="make,zrób"/>
		</item>
	</producer>

	<!-- Erna (Semos) -->
	<producer npc="Erna" slot="erna_bake_bread" type="food">
		<welcome text="Witaj w piekarni w Semos! Możemy upiec pyszny chleb dla każdego kto pomoże nam, przynosząc #mąkę z młyna. Powiedz tylko #'upiecz'."/>
		<item name="chleb" minutes="10">
			<resource name="mąka" amount="2"/>

			<activity type="bake,upiecz"/>
		</item>
	</producer>

	<!-- Kroip (Wo'fol) -->
	<producer npc="Kroip" slot="kroip_make_pizza" type="food">
		<welcome text="Witam! W czymś mogę #pomóc?"/>
		<item name="pizza" minutes="5">
			<resource name="mąka" amount="2"/>
			<resource name="ser"/>
			<resource name="pomidor"/>
			<resource name="borowik"/>
			<resource name="szynka"/>
			<resource name="pieczarka" amount="2"/>

			<activity type="make,zrób,upiecz"/>
		</item>
	</producer>

	<!-- Ernest (Gdańsk) -->
	<producer npc="Ernest" slot="ernest_make_donuts" type="food">
		<welcome text="Witaj w mojej piekarni, gdzie robię ciasto o przepysznej nazwie #pizza oraz #'pączki'!"/>
		<item name="pączek" minutes="3">
			<resource name="mąka"/>
			<resource name="mleko"/>
			<resource name="jajo"/>
			<resource name="osełka masła"/>
			<resource name="cukier"/>

			<activity type="make,zrób,upiecz"/>
		</item>
	</producer>

	<!-- Lena (Gdańsk) -->
	<producer npc="Lena" slot="lena_bake_bread" type="food">
		<welcome text="Witamy serdecznie w naszej pięknie pachnącej pieczywem piekarni!"/>
		<item name="chleb" minutes="6">
			<resource name="mąka" amount="2"/>

			<activity type="bake,upiecz"/>
		</item>
	</producer>

	<!-- Edna (Kraków) -->
	<producer npc="Edna" slot="edna_bake_bread" type="food">
		<welcome text="Witaj w naszej piekarni! Mogę dla ciebie upiec #'chleb'."/>
		<item name="chleb" minutes="7">
			<resource name="mąka" amount="2"/>

			<activity type="bake,upiecz"/>
		</item>
	</producer>

	<!-- Lanosz (Kraków) -->
	<producer npc="Lanosz" slot="lanosz_make_sandwich" type="food">
		<welcome text="Witaj w naszej piekarni! Przyszedłeś skosztować naszych specjalnych #kanapek?"/>
		<item name="kanapka z tuńczykiem" minutes="2">
			<resource name="chleb"/>
			<resource name="tuńczyk" amount="2"/>
			<resource name="pomidor"/>
			<resource name="sałata"/>

			<activity type="make,zrób"/>
		</item>
	</producer>

	<!-- Szef Piotruś (Tarnów) -->
	<producer npc="Szef Piotruś" slot="piotrus_make_potatoes" type="food">
		<welcome text="Witaj! W obecnej chwili wszyscy ludzie wraz z rycerzami są poza miastem. Podejrzewam, że niedługo oni wrócą! Jeśli chciałbyś skosztować moje pyszne ziemniaczki powiedz mi tylko #ugotuj."/>
		<item name="gotowane ziemniaki" quantity="5" minutes="1">
			<resource name="ziemniaki" amount="5"/>
			<resource name="butelka wody" amount="2"/>

			<activity type="make,zrób,ugotuj"/>
		</item>
	</producer>

	<!-- Małgosia (Zakopane) -->
	<producer npc="Małgosia" slot="malgosia_bake_bread" type="food">
		<welcome text="Witaj w piekarni w Zakopanem! Możemy upiec pyszny chleb dla każdego kto pomoże nam przynosząc mąkę z młyna. Powiedz tylko #upiecz."/>
		<item name="chleb" minutes="7">
			<resource name="mąka" amount="2"/>

			<activity type="bake,zrób,upiecz"/>
		</item>
	</producer>

	<!-- Jaś (Zakopane) -->
	<producer npc="Jaś" slot="jas_make_carrot_pie" type="food">
		<welcome text="Witaj w mojej piekarni! Chcesz spróbować moich placków z marchewką? Mogę #upiec jeden dla Ciebie!"/>
		<item name="tarta z marchewką" minutes="4">
			<resource name="mąka"/>
			<resource name="marchew" amount="2"/>
			<resource name="por"/>

			<activity type="bake,zrób,upiecz"/>
		</item>
	</producer>

	<!-- Elwirka (Zakopane) -->
	<producer npc="Elwirka" slot="elwirka_make_dwojaki" type="food">
		<welcome text="Witojcie! Co was tu sprowadza? Pewnie moje legendarne #dwojaki."/>
		<item name="dwojaki" minutes="5">
			<resource name="ziemniaki" amount="3"/>
			<resource name="kiełbasa wiejska" amount="3"/>
			<resource name="cebula"/>
			<resource name="osełka masła"/>
			<resource name="mleko"/>

			<activity type="make,zrób,ugotuj"/>
		</item>
	</producer>

</producers>

=== PolanieOnLine/PolanieOnLine/data/conf/producers/drinks.xml
<?xml version="1.0" encoding="UTF-8"?>

<producers xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../producers.xsd">

	<!-- Valo (Ados) -->
	<producer npc="Valo" slot="valo_concoct_potion" type="drink">
		<welcome text="Pozdrawiam młodzieńcze. #Uleczę Cię i #pomogę Tobie."/>
		<item name="wielki eliksir" minutes="2">
			<resource name="money" amount="20"/>
			<resource name="serce olbrzyma"/>

			<activity type="concoct,zrób,sporządź"/>
		</item>
	</producer>

	<!-- Uncle Dag (Ados) -->
	<producer npc="Uncle Dag" slot="uncle_dag_brew_fierywater" type="drink">
		<welcome text="Cześć! Jestem Uncle Dag, gorzelnik! Jeżeli przyniesiesz mi #'trzcinę cukrową' i #polano to #wywarzę dla Ciebie #'ekstrakt litworowy'."/>
		<item name="ekstrakt litworowy" minutes="20">
			<resource name="trzcina cukrowa" amount="5"/>
			<resource name="polano"/>

			<activity type="brew,nawarz"/>
		</item>
	</producer>

	<!-- Pedro (Athor) -->
	<producer npc="Pedro" slot="barman_mix_pina" type="drink">
		<welcome text="Aloha!"/>
		<item name="napój z oliwką" minutes="2">
			<resource name="kokos"/>
			<resource name="ananas"/>

			<activity type="mix,wymieszaj,zrób"/>
		</item>
	</producer>

	<!-- babcia Graham (Kalavan) -->
	<producer npc="babcia Graham" slot="granny_brew_tea" type="drink">
		<welcome text="Cześć. W czymś mogłabym #pomóc?"/>
		<item name="filiżanka herbaty" minutes="3">
			<resource name="mleko"/>
			<resource name="miód"/>

			<activity type="brew,zaparz"/>
		</item>
	</producer>

	<!-- Aron (Gdańsk) -->
	<producer npc="Aron" slot="aron_concoct_potion" type="drink">
		<welcome text="Witaj poszukiwaczu, co Ciebie sprowadza do mojej TAJNEJ kryjówki? Chcesz być moim #'królikiem doświadczalnym'?"/>
		<item name="duży smoczy eliksir" minutes="2">
			<resource name="money" amount="80"/>
			<resource name="gigantyczny eliksir"/>
			<resource name="smocza krew" amount="3"/>

			<activity type="concoct,zrób,sporządź"/>
		</item>
	</producer>

	<!-- Ojciec Honorat (Kraków) -->
	<producer npc="Ojciec Honorat" slot="honorat_concoct_potion" type="drink">
		<welcome text="Pozdrawiam młodzieńcze. W czym mogę Tobie #'pomóc'?"/>
		<item name="duży eliksir" minutes="2">
			<resource name="money" amount="20"/>
			<resource name="truchło wampira"/>
			<resource name="sclaria" amount="2"/>

			<activity type="concoct,zrób,sporządź"/>
		</item>
	</producer>

	<!-- Zbyszko (Kraków) -->
	<producer npc="Zbyszko" slot="zbyszko_make_vine" type="drink">
		<welcome text="Witajże, co szukasz w mym domu? Potrzebujesz #pomocy?"/>
		<item name="napój z winogron" minutes="1">
			<resource name="kiść winogron" amount="2"/>

			<activity type="make,zrób"/>
		</item>
	</producer>

	<!-- Agrypin (Wieliczka) -->
	<producer npc="Agrypin" slot="agrypin_concoct_potion" type="drink">
		<welcome text="Witaj rycerzu, nie chciałbyś czasem wypróbować mojego nowego #'eliksiru'?"/>
		<item name="smoczy eliksir" minutes="1">
			<resource name="money" amount="60"/>
			<resource name="wielki eliksir"/>
			<resource name="smocza krew"/>

			<activity type="concoct,zrób,sporządź"/>
		</item>
	</producer>

	<!-- Nosiwoda Gerwazy (Zakopane) -->
	<producer npc="Nosiwoda Gerwazy" slot="nosiwoda_fill_buklak" type="drink">
		<welcome text="Witaj [name]! Jeżeli przyniesiesz mi #'pusty bukłak' to naleję do niego wody ze źródełka. Powiedz tylko #nalej."/>
		<item name="bukłak z wodą" minutes="1">
			<resource name="pusty bukłak"/>
			<resource name="money" amount="140"/>

			<activity type="fill,nalej"/>
		</item>
	</producer>

	<!-- Nosiwoda Witek (Zakopane) -->
	<producer npc="Nosiwoda Witek" slot="nosiwoda_fill_buteleczke" type="drink">
		<welcome text="Witaj [name]! Jeżeli przyniesiesz mi #buteleczkę to naleję Tobie do niej wody ze źródełka. Powiedz tylko #nalej."/>
		<item name="buteleczka wody" minutes="1">
			<resource name="buteleczka"/>
			<resource name="money" amount="70"/>

			<activity type="fill,nalej"/>
		</item>
	</producer>

	<!-- Nosiwoda Jakub (Zakopane) -->
	<producer npc="Nosiwoda Jakub" slot="nosiwoda_fill_buklak" type="drink">
		<welcome text="Witaj [name]! Jeżeli przyniesiesz mi #butelkę to naleję Tobie do niej wody ze źródełka. Powiedz tylko #nalej."/>
		<item name="butelka wodą" minutes="1">
			<resource name="butelka"/>
			<resource name="money" amount="100"/>

			<activity type="fill,nalej"/>
		</item>
	</producer>

</producers>
